# Generated by Django 3.2.6 on 2021-08-17 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_owner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='program',
            table='programs',
        ),
    ]
