# Generated by Django 3.2.6 on 2021-08-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_alter_program_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('created_at',)},
        ),
    ]
